eureka:
  client:
    serviceUrl:
      #defaultZone:  http://localhost:8761/eureka
      defaultZone:  http://eureka:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, true
      routes:
        - id: clientes
          uri: lb://trip-service
          predicates:
            - Path=/client/**
        - id: trips
          uri: lb://trip-service
          predicates:
            - Path=/trip/**
        - id: passengers
          uri: lb://trip-service
          predicates:
              - Path=/passenger/**
        - id: tickets
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/**
        - id: trips
          uri: lb://ticket-service
          predicates:
            - Path=/generateTicket/**
